# Generated by Django 3.1 on 2020-09-01 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='image_url',
            new_name='image',
        ),
    ]
