# Generated by Django 3.1 on 2020-09-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200901_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watchlist_user', models.CharField(max_length=64)),
                ('watchlist_listing', models.CharField(max_length=64)),
            ],
        ),
    ]
