# Generated by Django 3.1 on 2020-09-02 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='watchlist_listing',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='watchlist_user',
            new_name='user',
        ),
    ]
