# Generated by Django 3.1 on 2020-09-02 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200902_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='title',
            new_name='watchlist_title',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='user',
            new_name='watchlist_user',
        ),
    ]
